name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/arm64 -t dltkdgus482/raspberrypi4:latest -f ./client/Dockerfile --push ./client

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          key: ${{ secrets.RPI_SSH_KEY }}
          port: ${{ secrets.RPI_PORT }}
          script: |
            docker pull dltkdgus482/raspberrypi4:latest
            docker stop local_server || true
            docker rm local_server || true
            docker run -d --name local_server -p ${{ secrets.WEB_PORT }}:3000 dltkdgus482/raspberrypi4:latest
